# Generated by Django 4.2.1 on 2023-05-25 14:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Historic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField(max_length=5000)),
                ('response', models.TextField(max_length=5000)),
                ('language', models.CharField(max_length=50)),
                ('date', models.DateTimeField(auto_now=True)),
                ('type', models.CharField(choices=[('correction', 'correction'), ('creation', 'creation'), ('general', 'general')], max_length=20, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='historic', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
